---
driver:
  name: vagrant

driver_config:
  network:
  - ["forwarded_port", {guest: 80, host: 8080, host_ip: "127.0.0.1"}]
  - ["forwarded_port", {guest: 443, host: 8443, host_ip: "127.0.0.1"}]
  - ["forwarded_port", {guest: 8080, host: 9080, host_ip: "127.0.0.1"}]
  - ["forwarded_port", {guest: 8443, host: 9443, host_ip: "127.0.0.1"}]  

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[venafi-helper-tomcat::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
