---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: httpd-tpp
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 8443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-httpd::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-httpd:
        url: 'https://venafi-ecosystem-tpp.cld.sr/vedsdk/'
        username: "<%= ENV['VENAFI_USERNAME'] %>"
        password: "<%= ENV['VENAFI_PASSWORD'] %>"
        zone: 'Venafi Partners\Indellient\Infra'
        common_name: 'test.example.com'
        location: '/etc/venafi'
        app_info: 'test'
        tls_address: '33.33.33.33:443'
        app_name: 'app_name'
        renew_threshold: 1
  - name: http-cloud
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 10080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 10443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-httpd::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-httpd:
        apikey: "<%= ENV['VENAFI_APIKEY'] %>"
        zone: '582d5560-a9a7-11ea-8a4f-3f9fa45442b2'
        common_name: 'test.indellient.com'
        location: '/etc/venafi'
        renew_threshold: 15
  - name: nginx-tpp
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 8443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-nginx:
        url: 'https://venafi-ecosystem-tpp.cld.sr/vedsdk/'
        username: "<%= ENV['VENAFI_USERNAME'] %>"
        password: "<%= ENV['VENAFI_PASSWORD'] %>"
        zone: 'Venafi Partners\Indellient\Infra'
        common_name: 'test.example.com'
        location: '/etc/venafi'
        app_info: 'test'
        tls_address: '33.33.33.33:443'
        app_name: 'app_name'
        renew_threshold: 1
  - name: nginx-cloud
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 10080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 10443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-nginx::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-nginx:
        apikey: "<%= ENV['VENAFI_APIKEY'] %>"
        zone: '582d5560-a9a7-11ea-8a4f-3f9fa45442b2'
        common_name: 'test.indellient.com'
        location: '/etc/venafi'
        renew_threshold: 15
  - name: tomcat-tpp
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 8443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-tomcat::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-tomcat:
        url: 'https://venafi-ecosystem-tpp.cld.sr/vedsdk/'
        username: "<%= ENV['VENAFI_USERNAME'] %>"
        password: "<%= ENV['VENAFI_PASSWORD'] %>"
        zone: 'Venafi Partners\Indellient\Infra'
        common_name: 'test.example.com'
        location: '/etc/venafi'
        app_info: 'test'
        tls_address: '33.33.33.33:443'
        app_name: 'app_name'
        renew_threshold: 1
  - name: tomcat-cloud
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 10080, host_ip: "127.0.0.1"}]
      - ["forwarded_port", {guest: 443, host: 10443, host_ip: "127.0.0.1"}]
    run_list:
      - recipe[venafi-helper-tomcat::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      venafi-helper-tomcat:
        apikey: "<%= ENV['VENAFI_APIKEY'] %>"
        zone: '582d5560-a9a7-11ea-8a4f-3f9fa45442b2'
        common_name: 'test.indellient.com'
        location: '/etc/venafi'
        renew_threshold: 15
