name 'venafi-helper'
maintainer 'Indellient'
maintainer_email 'help@indellient.com'
license 'All Rights Reserved'
description 'Install vcert and enrolls with a local TPP server or Venafi cloud'
version '1.0.0'
chef_version '>= 12.14'
issues_url 'https://github.com/Indellient/chef-infra-venafi-cookbook/issues'
source_url 'https://github.com/Indellient/chef-infra-venafi-cookbook'
depends 'ssl_certificate'
